package by.epam.mtlcwtchr.ecafe.controller.command;

public enum  WebCommandType {

    HOME_COMMAND,
    PROFILE_COMMAND,
    SIGN_IN_COMMAND,
    SIGN_UP_COMMAND,
    SIGN_OUT_COMMAND,
    CHANGE_PROFILE_COMMAND,
    MEALS_COMMAND,
    CATEGORIES_COMMAND,
    CLIENT_ORDER_COMMAND,
    CLIENT_ORDERS_COMMAND,
    LOAD_IMAGE_COMMAND,
    ADD_MEAL_TO_ORDER_COMMAND,
    REMOVE_MEAL_FROM_ORDER_COMMAND,
    PAYMENT_COMMAND,
    PLACE_ORDER_COMMAND,

    AORDERS_COMMAND,
}
