package by.epam.mtlcwtchr.ecafe.service.command;

public enum CommandType {

    GET_MEALS_COMMAND,
    GET_INGREDIENTS_COMMAND,
    GET_CATEGORIES_COMMAND,
    GET_ORDERS_COMMAND,
    GET_USERS_COMMAND,
    GET_CLIENTS_COMMAND,

    GET_MEAL_COMMAND,
    GET_INGREDIENT_COMMAND,
    GET_CATEGORY_COMMAND,
    GET_ORDER_COMMAND,
    GET_USER_COMMAND,
    GET_CLIENT_COMMAND,

    SAVE_MEAL_COMMAND,
    SAVE_INGREDIENT_COMMAND,
    SAVE_CATEGORY_COMMAND,
    PLACE_ORDER_COMMAND,

    UPDATE_MEAL_COMMAND,
    UPDATE_INGREDIENT_COMMAND,
    UPDATE_CATEGORY_COMMAND,
    UPDATE_ORDER_COMMAND,
    UPDATE_USER_COMMAND,
    UPDATE_CLIENT_COMMAND,

    DELETE_MEAL_COMMAND,
    DELETE_INGREDIENT_COMMAND,
    DELETE_CATEGORY_COMMAND,
    DELETE_ORDER_COMMAND,
    DELETE_USER_COMMAND,
    DELETE_CLIENT_COMMAND,

    AUTHORIZATE_COMMAND

}
